name: finansional_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/gas-station.png
    - assets/images/mcdonalds.png
    - assets/images/menu.png
    - assets/images/profile.png




  fonts:
    - family: Khang
      fonts:
        - asset: assets/fonts/Khang-Light.ttf
          weight: 300
        - asset: assets/fonts/Khang-Regular.ttf
          weight: 400
        - asset: assets/fonts/Khang-Medium.ttf
          weight: 500
        - asset: assets/fonts/Khang-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Khang-Bold.ttf
          weight: 700
